# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai',
                'doc_host': 'https://masibasi.github.io',
                'git_url': 'https://github.com/masibasi/fastai',
                'lib_path': 'fastai'},
  'syms': {'fastai.core': {'fastai.core.foo': ('core.html#foo', 'fastai/core.py')}}}
